name: run API2.py

on:
  ##schedule:
  ##- cron: '*/10 * * * *'
  
  workflow_dispatch:
  

jobs:
  Actions-API:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python
        run: python API2.py
      

